server.port=8080

# Firebase Config
firebase.config-path=classpath:firebase-service-account.json

# Allow definition overriding
spring.main.allow-bean-definition-overriding=true

# Twilio Configuration
twilio.account-sid=${TWILIO_ACCOUNT_SID:placeholder-account-sid}
twilio.auth-token=${TWILIO_AUTH_TOKEN:placeholder-auth-token}
twilio.from-number=${TWILIO_FROM_NUMBER:placeholder-from-number}
