server.port=8080

# Firebase Config
firebase.config-path=classpath:firebase-service-account.json

# Allow definition overriding
spring.main.allow-bean-definition-overriding=true

# Twilio Configuration
twilio.account-sid=placeholder-account-sid
twilio.auth-token=placeholder-auth-token
twilio.from-number=placeholder-from-number
